# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
sphinx:
  configuration: docs/conf.py

build:
  apt_packages:
    - pandoc

python:
  version: 3.8
  install:
    - path: .
      extra_requirements: [doc]
